name = "burger-bong-api"
main = "worker/src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "burger_bong_db"
database_id = "4c624c7c-93d4-492e-9ec4-e6293942ed0a"
migrations_dir = "worker/migrations"

# Uncomment if you need file storage (Cloudflare R2)
# [[r2_buckets]]
# binding = "BURGER_BONG_FILES"
# bucket_name = "burger-bong-files"
# jurisdiction = "eu"
